Repository ga-devfront/scroll-event-handler, pull requests merged in 2020-06, with the labels that each got.

#50 🐛 fix Adding passive argument to addEventListener #49
  index.js
Labels: bug

#51 Create CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#52 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: documentation

#53 Add community guide for Pull Request and Issue creation
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/custom.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  index.js
Labels: documentation, enhancement

#56 Feature#55
  README.md
  package.json
Labels: documentation, enhancement

#57 Develop
  README.md
  package.json
Labels: documentation, enhancement

#60 Develop
  index.js
  package.json
Labels: enhancement
