Repository ga-devfront/scroll-event-handler, pull requests merged in 2020-04, with the labels that each got.

#2 Feature#1
  index.html
  index.js
  test.js
Labels: enhancement

#4 Feature#3
  index.html
  index.js
  test.js
Labels: enhancement

#7 Feature#3
  index.html
  index.js
  test.js
Labels: enhancement

#8 Feaure#5
  index.js
  test.js
Labels: enhancement

#10 Feature#9
  README.md
Labels: documentation

#14 ✨ add language tags in code blocks
  README.md
Labels: documentation

#16 Feature#15
  demo/demo.js
  demo/index.html
  index.js
Labels: bug, enhancement

#18 Feature#17
  .eslintrc.js
  .gitignore
  demo/demo.js
  index.js
  package-lock.json
  package.json
Labels: enhancement

#20 Feature#19
  demo/demo.js
  index.js
Labels: enhancement

#23 Feature#21
  README.md
  package.json
Labels: documentation

#24 Feature#22
  index.js
Labels: enhancement

#28 🐛 fix changeSettings and comments
  index.js
Labels: bug

#29 Develop
  index.js
Labels: bug

#30 Feature#25
  demo/demo.css
  demo/demo.js
  demo/img/github.png
  demo/img/npm.png
  demo/index.html
Labels: enhancement

#31 Feature#26
  README.md
  package.json
Labels: documentation

#37 Feature#36
  README.md
Labels: documentation

#39 Feature#38
  README.md
  package.json
Labels: documentation

#41 🐛 fix link bug
  README.md
Labels: bug, documentation

#43 Feature#42
  index.js
  package.json
Labels: bug
